apiVersion: "acid.zalan.do/v1"
kind: "postgresql"
metadata:
  name: "vault-postgres"
  namespace: "vaultwarden"
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    zalando:
    - superuser
    - createdb
    vaultwarden: []
  databases:
    vaultwarden: vaultwarden
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
